apiVersion: v2
name: jitendragpdt-dev
description: A Helm chart for Kubernetes
type: application
version: 0.2.0
appVersion: 1.0
dependencies:
- name: miabusinessapp
  version: 3.1.1
  repository: oci://harbor.redchimney.com/dockerhub/mrcenter
